"""initial schema

Revision ID: 305114eba5df
Revises: 
Create Date: 2026-06-07 16:48:35.164273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '305114eba5df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('min_employee_count', sa.Integer(), nullable=False),
    sa.Column('job_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recruiter_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('high_volume_role_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_decision_maker_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_table('integration_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('openai_api_key', sa.String(length=512), nullable=True),
    sa.Column('openai_base_url', sa.String(length=512), nullable=True),
    sa.Column('openai_model', sa.String(length=128), nullable=True),
    sa.Column('firecrawl_api_key', sa.String(length=512), nullable=True),
    sa.Column('jobspy_enabled', sa.Boolean(), nullable=False),
    sa.Column('hunter_api_key', sa.String(length=512), nullable=True),
    sa.Column('zerobounce_api_key', sa.String(length=512), nullable=True),
    sa.Column('apollo_api_key', sa.String(length=512), nullable=True),
    sa.Column('reacher_api_url', sa.String(length=512), nullable=True),
    sa.Column('baserow_api_url', sa.String(length=512), nullable=True),
    sa.Column('baserow_api_key', sa.String(length=512), nullable=True),
    sa.Column('twenty_api_url', sa.String(length=512), nullable=True),
    sa.Column('twenty_api_key', sa.String(length=512), nullable=True),
    sa.Column('hubspot_api_key', sa.String(length=512), nullable=True),
    sa.Column('n8n_webhook_url', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_settings_user_id'), 'integration_settings', ['user_id'], unique=True)
    op.create_table('company_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('careers_url', sa.String(length=512), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('total_open_jobs', sa.Integer(), nullable=False),
    sa.Column('recruiter_jobs_open', sa.Integer(), nullable=False),
    sa.Column('ta_coordinator_jobs', sa.Integer(), nullable=False),
    sa.Column('high_volume_role_jobs', sa.Integer(), nullable=False),
    sa.Column('has_urgent_hiring', sa.Boolean(), nullable=False),
    sa.Column('has_multiple_locations', sa.Boolean(), nullable=False),
    sa.Column('has_stale_jobs', sa.Boolean(), nullable=False),
    sa.Column('locations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_maker_name', sa.String(length=255), nullable=True),
    sa.Column('decision_maker_title', sa.String(length=255), nullable=True),
    sa.Column('decision_maker_email', sa.String(length=255), nullable=True),
    sa.Column('decision_maker_email_status', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_pain_hypothesis', sa.Text(), nullable=True),
    sa.Column('ai_bandwidth_pressure', sa.Text(), nullable=True),
    sa.Column('ai_buyer_persona', sa.Text(), nullable=True),
    sa.Column('ai_outreach_angle', sa.Text(), nullable=True),
    sa.Column('ai_cold_email', sa.Text(), nullable=True),
    sa.Column('ai_linkedin_message', sa.Text(), nullable=True),
    sa.Column('ai_whatsapp_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_leads_campaign_id'), 'company_leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_company_leads_company_name'), 'company_leads', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_leads_priority'), 'company_leads', ['priority'], unique=False)
    op.create_index(op.f('ix_company_leads_score'), 'company_leads', ['score'], unique=False)
    op.create_index(op.f('ix_company_leads_user_id'), 'company_leads', ['user_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('companies_found', sa.Integer(), nullable=False),
    sa.Column('leads_created', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_campaign_id'), 'research_runs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_research_runs_status'), 'research_runs', ['status'], unique=False)
    op.create_index(op.f('ix_research_runs_user_id'), 'research_runs', ['user_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_lead_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('posted_date', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('is_recruiter_role', sa.Boolean(), nullable=False),
    sa.Column('is_ta_coordinator', sa.Boolean(), nullable=False),
    sa.Column('is_high_volume_role', sa.Boolean(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_lead_id'], ['company_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_company_lead_id'), 'job_postings', ['company_lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_company_lead_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_research_runs_user_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_status'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_campaign_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_company_leads_user_id'), table_name='company_leads')
    op.drop_index(op.f('ix_company_leads_score'), table_name='company_leads')
    op.drop_index(op.f('ix_company_leads_priority'), table_name='company_leads')
    op.drop_index(op.f('ix_company_leads_company_name'), table_name='company_leads')
    op.drop_index(op.f('ix_company_leads_campaign_id'), table_name='company_leads')
    op.drop_table('company_leads')
    op.drop_index(op.f('ix_integration_settings_user_id'), table_name='integration_settings')
    op.drop_table('integration_settings')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
